Update the install script to use "modules".
Next we need to have each install script put the dotfiles into the
correct place so we can move the dotfiles repo out of the $HOME
directory.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,64 +1,53 @@
 #!/bin/bash
+set -e
 
-if [[ $EUID -ne 0 ]]; then
-    echo "Must be run as root."
+red=`tput setaf 1`
+green=`tput setaf 2`
+reset=`tput sgr0`
+
+USER=$1
+
+# Ensure this script is called by the root user.
+if [[ "`whoami`" != "root" ]]; then
+    echo "You must run this script as root."
     exit 1
 fi
 
-# Setup the locale.
-sed -ie "s/#en_US\.UTF/en_US.UTF/" /etc/locale.gen
-locale-gen
-echo "LANG=en_US.UTF-8" > /etc/locale.conf
+# Ensure root dotfiles have been installed before any other users.
+if [[ ! -f /root/.dotfiles ]] && [[ "$USER" != "root" ]]; then
+    echo "You must first run \`./install root\`."
+    exit 1
+fi
 
-# Setup the timezone for correct local system time.
-timedatectl set-timezone America/Denver
+# Create the user (if needed).
+if ! id -u $USER &> /dev/null; then
+    # TODO: flag for sudo group.
+    useradd -m -G wheel -s /usr/bin/fish $USER
+fi
 
-# Set the system clock to use NTP.
-timedatectl set-ntp true
+# Install each of the user's modules.
+if [[ -d $USER ]]; then
+    for module in $(ls $USER); do
+        cd $USER/$module
+        pretty_module=`echo $module | cut -d '_' -f2`
+        echo "${green}Installing $USER $pretty_module...${reset} "
+        if [[ "$USER" == "root" ]]; then
+            cmd="./install"
+        else
+            cmd="sudo -u $USER ./install"
+        fi
+        if ! $cmd &> /dev/null; then
+            echo "${red}failed${reset}."
+            exit 1
+        fi
+        cd ../..
+    done
+fi
 
-# TODO: Create a post-install unit that prompts users to check these settings.
-# We don't want to touch the host machine's clocks.
-#
-# # Set the hardware clock based on the system clock, however the HW clock
-# # will be set in UTC.
-# timedatectl set-local-rtc 0
-# hwclock --systohc
-
-# Setup sudo.
-pacman -S --noconfirm sudo
-chmod 440 /etc/sudoers
-chown root:root /etc/sudoers
-
-# Install dialog and wpa_supplicant for wifi-menu.
-pacman -S --noconfirm dialog wpa_supplicant
-
-# Install our favorite shell, to be used by all.
-pacman -S --noconfirm fish
-chsh -s /usr/bin/fish
-
-# Create our user account, with password-less sudo.
-useradd -m -G wheel -s /usr/bin/fish nixpulvis
-
-# Install git, it's the best thing since sliced bread.
-pacman -S --noconfirm git
-
-# Install this repository into root's Code directory.
-mkdir ~/Code
-git clone https://github.com/nixpulvis/arch.git ~/Code/arch
-
-# We develop.
-pacman -S --noconfirm base-devel
-
-# Vim is the *current* editor of choice. We need `gvim` for X11 clipboard
-# support.
-pacman -S --noconfirm gvim
-
-# TODO #1: Install these arch installer scripts.
-pacman -S --noconfirm dosfstools
-
-# TODO: Hostname
-# TODO #3: Passwords
-
-# TODO: Figure out a better way to call this script.
-sudo -iu nixpulvis /root/install_nixpulvis
+# Indicate we've install the dotfiles for $USER.
+if [[ "$USER" == "root" ]]; then
+    touch /root/.dotfiles
+else
+    touch /home/$USER/.dotfiles
+fi
 
